" Defaults
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Command autocompletion
set wildmode=longest:full,full

" Status bar
set laststatus=2

" Line numbering
set number
set relativenumber

" Line indentation
set tabstop=2
set shiftwidth=2
set softtabstop=2

" Bracket highlighting
set showmatch

" Search
set hlsearch

" Mouse support
set mouse=a

" Clipboard
set clipboard=unnamed

" Silence
set belloff=all

" Backup
set nobackup
set nowritebackup
set noswapfile

" Cursor
autocmd InsertEnter * set cursorline
autocmd InsertLeave * set nocursorline

" Window
set title

" Theme
" Install 
" - NLKNguyen/papercolor-theme
" - itchyny/lightline.vim
" - vimpostor/vim-lumen  
set noshowmode
colorscheme papercolor
let g:lightline = { 'colorscheme': 'PaperColor' }

